apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extlb-operator
rules:
- apiGroups: [""]
  resources: ["services","endpoints"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes","traefikservices"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["net.futhwo.io"]
  resources: ["externalbalancers","externalbalancers/status"]
  verbs: ["get","list","watch","update","patch"]
