apiVersion: v1
entries:
  externalbalancer-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-11-10T00:42:08.278793989+01:00"
    description: An operator that manages Traefik-based external load balancing for
      external backends.
    digest: ad184762e5e1a0e487682f739e65044ba1090c490f7a3cb3dc06e60e6e8e842d
    name: externalbalancer-operator
    type: application
    urls:
    - https://futhwo.github.io/externalbalancer/externalbalancer-operator-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-10T00:42:08.278377072+01:00"
