apiVersion: net.cdlan.io/v1alpha1
kind: ExternalBalancer
metadata:
  name: provaui
  namespace: default
spec:
  strategy: WeightedPerService
  ingressRouteLabels:
    traefik.io/ingress-controller: edge-a
  host: radius-traefik.cdlan.net
  entryPoints: ["websecure"]
  tlsSecretName: wildcard-cdlan-net
  stickyCookieName: lvl1
  useEndpointSlice: true
  backends:
    - name: provaui-1
      address: 10.129.33.191
      port: 9080
      weight: 1
      h2c: true
      stickyCookieName: lvl2
    - name: provaui-2
      address: 10.129.33.192
      port: 9080
      weight: 1
      h2c: true
      stickyCookieName: lvl2
