apiVersion: net.futhwo.io/v1alpha1
kind: ExternalBalancer
metadata:
  name: provaui
  namespace: test-ext-lb
spec:
  strategy: WeightedPerService
  ingressRouteLabels:
    ingress-scope: internal
  host: extlb-simple.futhwo.it
  entryPoints: ["websecure"]
  tlsSecretName: wildcard-futhwo-it
  stickyCookieName: lvl1
  useEndpointSlice: true
  backends:
    - name: provaui-1
      address: 10.11.12.13
      port: 9080
      weight: 1
      h2c: true
      stickyCookieName: lvl2
    - name: provaui-2
      address: 10.11.12.14
      port: 9080
      weight: 1
      h2c: true
      stickyCookieName: lvl2
