apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "externalbalancer-operator.fullname" . }}
  namespace: {{ include "externalbalancer-operator.namespace" . }}
  labels:
    app: {{ include "externalbalancer-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "externalbalancer-operator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "externalbalancer-operator.fullname" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ default (include "externalbalancer-operator.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ ternary "true" "false" .Values.leaderElection.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:8081
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            - name: healthz
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{- toYaml .Values.resources | nindent 12 }}
