apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalbalancers.net.futhwo.io
spec:
  group: net.futhwo.io
  scope: Namespaced
  names:
    plural: externalbalancers
    singular: externalbalancer
    kind: ExternalBalancer
    shortNames: [extlb]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [host, entryPoints, tlsSecretName, backends]
              properties:
                strategy:
                  type: string
                  enum: ["WeightedPerService","SingleService"]
                  default: "WeightedPerService"
                ingressRouteLabels:
                  type: object
                  additionalProperties:
                    type: string
                host:
                  type: string
                entryPoints:
                  type: array
                  items:
                    type: string
                tlsSecretName:
                  type: string
                stickyCookieName:
                  type: string
                useEndpointSlice:
                  type: boolean
                serviceTemplate:
                  type: object
                  properties:
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                backends:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: [name, address, port]
                    properties:
                      name:
                        type: string
                      address:
                        type: string
                      port:
                        type: integer
                        format: int32
                        minimum: 1
                      weight:
                        type: integer
                        format: int32
                      h2c:
                        type: boolean
                      stickyCookieName:
                        type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                ready:
                  type: boolean
                servicesCreated:
                  type: integer
                  format: int32
                endpointsCreated:
                  type: integer
                  format: int32
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
